#!/usr/bin/env bash
#displays Best School 10 times  and then Hi after 9th line
i=0
while [ $i -lt 10 ]; do
      echo "Best School"
      if [ $i == 8 ] ; then
      	 echo "Hi"
	 fi
	 let "i++"
done
